// Levels definition
var LEVELS = [
  {
    name: "PUSH",
    time: 25,
    timer: 60,
    map: [
      "####################",
      "####################",
      "###WWWWWWWWWWWWWW###",
      "###              ###",
      "###              ###",
      "###   BHHHHHH2   ###",
      "###              ###",
      "###              ###",
      "###              ###",
      "###              ###",
      "###  F@          ###",
      "###  V           ###",
      "###  LHHHHHHZ    ###",
      "####################",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      " 💬                  ",
      "        >  >        ",
      "  �               💬  ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    links: {"17,11_toggle":false,"17,11":1,"17,7":1,"17,9":1,"2,10":2,"2,8":2,"17,6_init":true},
    dialogues: {"1,5":{"trigger":"start","pos":"follow","messages":[{"text":"[speed:40][wave:1.5]Sistemas de Superfície...[/wave] [color:#00f0ff]ONLINE.","icon":"ai"},{"text":"Bem-vindo ao [highlight:#ff00ea]SETOR 00[/highlight].[pause:500]\nAperte [color:#ff00ea]ESPAÇO[/color] para prosseguir.","icon":"ai"}]}}
  },
  {
    name: "REDIRECT",
    time: 30,
    timer: 60,
    map: [
      "####################",
      "###WWWWWWWWWWWWWW###",
      "###              ###",
      "###              ###",
      "###        FHX   ###",
      "###        V     ###",
      "###  2HHHHHl   @ ###",
      "### ZHHHHHHH     ###",
      "###        LHB   ###",
      "###              ###",
      "###              ###",
      "####################",
      "WWWWWWWWWWWWWWWWWWWW",
      "                    ",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      " 💬      <   <       ",
      "                    ",
      "           <        ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    dialogues: {"1,5":{"trigger":"start","messages":[{"text":"[arcane:#00f0ff:#ff00ea]Energia Quântica detectada.[/arcane]\nOs prismas exigem [color:#00f0ff]foco quântico.","icon":"ai"},{"text":"[sfx:human]Alô? [pause:300]Consegue me ouvir?[/sfx]\n[shake:1]A estática está muito forte...[/shake]","icon":"human"}]}}
  },
  {
    name: "COMPLETE",
    time: 50,
    timer: 60,
    map: [
      "####################",
      "####################",
      "#WWWWWWWWWWWWWWWWWW#",
      "#                  #",
      "#                  #",
      "#                  #",
      "#                  #",
      "# BHCSFHCSFHCSFHH5 #",
      "#   L JSL JSL J    #",
      "#                  #",
      "#                  #",
      "# @                #",
      "#                  #",
      "####################",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "       >   >        ",
      "                    ",
      "                    ",
      "     >   >   >      ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    dialogues: {"1,5":{"trigger":"start","messages":[{"text":"[speed:10]ESTABILIZANDO PROTOCOLO...[/speed]\n[pause:800]Pronto. Conexão firme.","icon":"ai"},{"text":"[glitch:2]ADVERTÊNCIA![/glitch] [pause:500]\n[pulse:1]Radiação Beta acima do normal.[/pulse]","icon":"alert"}]}}
  },
  {
    name: "DUAL CORE",
    time: 50,
    timer: 60,
    map: [
      "####################",
      "WW#WWWWWWWWWWWWWW#WW",
      "  #     BCFX     #  ",
      "# #     #VV#     # #",
      "# #     #VV#     # #",
      "# #     #VV#     # #",
      "# # @   WVV#     # #",
      "# #      VV#     # ##",
      "# #     #VV#     # #",
      "# #     #VV#     # # ###",
      "# #     #VV#     # #",
      "# #     WVVW     # #",
      "W #     ZJLT     # W",
      "  #              #  ",
      "# ################ #",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "    v               ",
      "          v         ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    dialogues: {"1,5":{"trigger":"start","pos":"follow","messages":[{"text":"O núcleo duplo exige sincronia.\n[crypt:2]ALPHA-9-ZERO[/crypt]","icon":"ai"},{"text":"[shake:2]ALERTA DE PRESSÃO![/shake]\nNão toque nos componentes [color:#ff0000]RED[/color].","icon":"critical"}]}}
  },
  {
    name: "DIVERSION",
    time: 50,
    timer: 120,
    map: [
      "####################",
      "###WWWWWWWWWWWWWW###",
      "###              ###",
      "### F B HHdHHHX  ###",
      "### V     V      ###",
      "### V     V      ###",
      "### V     2      ###",
      "### V     V      ###",
      "### V     V      ###",
      "### V 3 HHJ      ###",
      "### V            ###",
      "### LH@          ###",
      "###              ###",
      "####################",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "     < <            ",
      "                    ",
      "                    ",
      "                    ",
      "            ^ >     ",
      "                    ",
      "            < v     ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    dialogues: {"1,5":{"trigger":"start","messages":[{"text":"[arcane:2:#00f0ff]Desvio de carga detectado.[/arcane]\nUse os [highlight:#ff00ea]Botões Roxos[/highlight] para alternar.","icon":"ai"},{"text":"[pixel:2]A imagem está pixelando...[/pixel]\n[sfx:human]O sistema está caindo?[/sfx]","icon":"human"}]}}
  },
  {
    name: "MAGNETIC BELT",
    time: 40,
    timer: 90,
    map: [
      "####################",
      "###WWWWWWWWWWWWWW###",
      "###              ###",
      "### @            ###",
      "###   ))))))     ###",
      "###   (    )     ###",
      "###   (    )     ###",
      "###   ((((((     ###",
      "###          B   ###",
      "###   [[[[[[ V   ###",
      "###   ]    [ V   ###",
      "###   ]]]]]] 2   ###",
      "###              ###",
      "####################",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "      >             ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    dialogues: {"1,5":{"trigger":"start","messages":[{"text":"[reboot:2]REINICIALIZANDO ESTEIRA...[/reboot]\n[pause:500]Fluxo magnético reativado.","icon":"ai"},{"text":"Cuidado com a [color:#00f0ff]Gravidade[/color].\nO cinto é implacável.","icon":"ai"}]}}
  },
  {
    name: "SACRIFICE",
    time: 50,
    timer: 120,
    map: [
      "####################",
      "#WWWWWWWWWWWWWW#####",
      "#              #####",
      "#  @           #####",
      "#              #WWW#",
      "#             FHC  #",
      "#             V#V  #",
      "#         B  HJ#V  #",
      "#              #V  #",
      "################V  #",
      "#         #FHHHHJ  #",
      "#         #V       #",
      "#         FT      ##",
      "#                KB#",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "           >        ",
      "                    ",
      "                    ",
      "                    ",
      "              <     ",
      "               >    ",
      "                    ",
      "                    ",
    ],
    overlays: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "  __))))))))   D    ",
      "      ((((((        ",
      "                    ",
      "                    ",
      "                    ",
      "   S   S S          ",
      "     S              ",
      "  S    S            ",
      "   S  S   D         ",
      "                    ",
    ],
    links: {"10,13":0,"2,5":1,"15,5":1,"3,5":1},
    dialogues: {"1,5":{"trigger":"start","pos":"follow","messages":[{"text":"[melt:3]O CALOR ESTÁ DERRETENDO O SENSOR![/melt]","icon":"critical"},{"text":"[sketch:2]A realidade está virando um desenho?[/sketch]\nIsso não estava no manual.","icon":"ai"}]}}
  },
  {
    name: "THE PIT",
    time: 100,
    timer: 120,
    map: [
      "####################",
      "#WWWWWWWWWWWWWWWWWW#",
      "#                  #",
      "#   BHHHHHHHHH2    #",
      "#                  #",
      "#   *****?****     #",
      "#   *****?****     #",
      "#   *****?****     #",
      "#        _         #",
      "#      @           #",
      "#                  #",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "        >           ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    overlays: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "   ))))     ((((    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "  G                 ",
      "                    ",
    ],
    links: {"9,8":1,"9,5":1,"9,6":1,"9,7":1}
  },
  {
    name: "SINGULARIDADE",
    time: 120,
    timer: 150,
    map: [
      "####################",
      "#WWWWWWWWWWWWWWWWWW#",
      "#                  #",
      "# BHHH    T1   B   #",
      "#              V   #",
      "#              V   #",
      "#              V   #",
      "#              V   #",
      "#              V   #",
      "#     @        T1  #",
      "#                  #",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "    y               ",
      "         p          ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    overlays: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "       !            ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ]
  },
  {
    name: "TESTDRIVE",
    time: 1000,
    timer: 600,
    map: [
      "######## ####F #####",
      "#WW       THH      #",
      "#                  #",
      "#                  #",
      "#                  #",
      "#********      ****#",
      "#                  #",
      "#                  #",
      "            G      #",
      "V F@               #",
      "V B    ^ < > v     #",
      "V           ##G##  #",
      "V      BX   *****  #",
      "V FdC  VV  G       #",
      "V r+l  VV      G  G#",
      "V L+J  VV         G#",
      "L HB   VV          #",
      "#      VV  #########",
      "#      VV  WWWW    #",
      "#      VV          #",
      "#      TT          #",
      "#                  #",
      "#                  #",
      "# ******           #",
      "# *******          #",
      "# *******          #",
      "# ********         #",
      "#*********         #",
      "#*******           #",
      "# ******           #",
      "# *****##          #",
      "#                  #",
      "#                  #",
      "#      #######  ####",
      "#       #          #",
      "#       # ####  ####",
      "#         #  #  #  #",
      "#         #        #",
      "# # # # ###  #    ##",
      "####################",
    ],
    blocks: [
      "💬                   ",
      "                    ",
      "                    ",
      "      >             ",
      "  >     >⚡y   p     ",
      "          yy pp     ",
      "           p  p     ",
      "                    ",
      " >            M     ",
      "                    ",
      "                    ",
      "   >       M        ",
      "                    ",
      "            MMM   M ",
      "             M   M  ",
      " <       v M     M  ",
      "      v     M     M ",
      "                    ",
      "                    ",
      "    >               ",
      "  >                 ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "   p              > ",
      " p  y p          >  ",
      "              ⚡     ",
      "         >        > ",
      " y                  ",
      "                    ",
      "        ⚡           ",
      " ⚡ ⚡ ⚡ ⚡            ",
      "                    ",
    ],
    overlays: [
      "        D     D     ",
      "    O O _    Q      ",
      "                 ]  ",
      "       _    !    ]  ",
      "   ???           ]  ",
      "   ???           ]  ",
      "   ???           ]  ",
      "   ???    _      ]  ",
      "D       _ E      ]  ",
      " _   ))))))))))SSSS ",
      "               SSSS ",
      "                 SS ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                 O  ",
      "                    ",
      "    ]           wne ",
      "    ]            s  ",
      "    ]               ",
      "    ]      ))))))]  ",
      "    ]     [      ]  ",
      "    ][    [      ]  ",
      "    )[    [ ](((((  ",
      "          [ ]       ",
      "          [ ]       ",
      "          [((       ",
      "  D    ??           ",
      "       ??           ",
      "  E                 ",
      "                    ",
      "                    ",
      "   O                ",
      "                    ",
      "                    ",
      "                    ",
    ],
    links: {"7,3":2,"2,9_toggle":true,"1,11_toggle":true,"1,9":1,"0,8":1,"7,3_behavior":"TOGGLE","14,1_behavior":"PERMANENT","14,1":3,"14,0":3,"8,1_behavior":"PRESSURE","8,1":4,"8,0":4,"10,7_behavior":"PRESSURE","10,7_init":true,"10,7":8,"5,9":8,"6,9":8,"7,9":8,"8,9":8,"9,9":8,"10,9":8,"11,9":8,"12,9":8,"13,9":8,"14,9":8,"17,2":15,"17,3":15,"17,4":15,"17,5":15,"17,6":15,"17,7":15,"17,8":15,"1,21_dir":0,"7,3_init":false,"8,8":11,"8,8_behavior":"TOGGLE","8,8_init":true,"10,8":11,"14,8_dir":1,"14,8_behavior":"3","3,4":2,"4,4":2,"5,4":2,"3,5":2,"4,5":2,"5,5":2,"3,6":2,"4,6":2,"3,7":2,"4,7":2,"5,7":2,"5,6":2,"17,19":5,"6,1":5,"6,1_color":"#ff0000","17,19_color":"#ff0000","4,1":9,"4,1_color":"#00e1ff","3,36":9,"3,36_color":"#00e1ff","14,13_dir":3,"18,13_dir":1,"18,16_dir":2,"12,16_dir":3,"12,13_dir":0,"13,13_dir":1,"13,14_dir":3,"17,14_dir":1,"17,15_dir":2,"11,15_dir":3,"11,11_dir":0,"7,31":29,"8,31":29,"7,32":29,"8,32":29,"10,8_dir":0,"11,5_dir":1,"10,5_dir":2,"13,5_dir":1,"14,4_dir":2,"2,33_dir":2,"2,33_init":false,"2,33":20,"2,31":20},
    dialogues: {"0,0":{"trigger":"start","radius":0,"oneShot":true,"lockPlayer":false,"autoDismiss":true,"messages":[{"text":"Nova fala...","icon":"ai","trigger":"walk","isAI":true}]}},
    zoneTriggers: [{"x":14,"y":33,"radius":1,"oneShot":true,"events":[{"type":"blackout","action":"deactivate"},{"type":"music_intensity","action":"3"},{"type":"earthquake","action":"90"},{"type":"wait","action":"30"}],"w":2,"h":1,"offX":0,"offY":0},{"x":8,"y":37,"radius":1,"oneShot":true,"events":[{"type":"blackout","action":"activate"},{"type":"music_intensity","action":"1"},{"type":"earthquake","action":"90"},{"type":"remote_signal","action":"activate","channel":"20"}],"w":1,"h":2,"offX":0,"offY":-1},{"x":3,"y":38,"radius":0,"oneShot":false,"events":[{"type":"remote_signal","action":"toggle","channel":"20"}]},{"x":5,"y":38,"radius":0,"oneShot":true,"events":[{"type":"gravity","action":"left"}]},{"x":7,"y":38,"radius":0,"oneShot":false,"events":[{"type":"dimension_shift","action":"solar"},{"type":"wait","action":"30"},{"type":"dimension_shift","action":"lunar"}]},{"x":1,"y":38,"radius":0,"oneShot":true,"events":[{"type":"security_alert","action":"activate"},{"type":"wait","action":"200"},{"type":"security_alert","action":"deactivate"}]}]
  }
];

var CHAPTERS = [
  {
    "name": "TRIAGEM DE CARGA E FLUXO ESTÁTICO",
    "levels": [
      0,
      1,
      2,
      3
    ]
  },
  {
    "name": "LOGÍSTICA DE CONTENÇÃO PRIMÁRIA",
    "levels": [
      4,
      5,
      6
    ]
  },
  {
    "name": "PAVILHÃO DE PROCESSAMENTO EM FLUXO",
    "levels": []
  },
  {
    "name": "ABISMO DE SUSTENTAÇÃO QUÂNTICA",
    "levels": [
      7,
      8
    ]
  },
  {
    "name": "LABORATÓRIO DE REFRAÇÃO E CONVERGÊNCIA",
    "levels": []
  },
  {
    "name": "ZONA DE OBSERVAÇÃO DO VÁCUO",
    "levels": []
  },
  {
    "name": "HUB DE ENTRELAÇAMENTO NÃO-EUCLIDIANO",
    "levels": []
  },
  {
    "name": "ÁREA DE TESTES: VETORES DE GRAVIDADE",
    "levels": []
  },
  {
    "name": "CÂMARA DE DEPURAÇÃO DE REALIDADE",
    "levels": []
  },
  {
    "name": "O COMPILADOR MESTRE",
    "levels": [
      9
    ]
  }
];
