// Levels definition
var LEVELS = [
  {
    name: "RECEPÇÃO SETOR 00",
    map: [
      "AAAAAAAAAAAAAAA",
      "AfifiiiffiffffA",
      "AaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaA",
      "AAAAAaAAAAAAAAA",
      "fffffUfffffffff",
    ],
    overlays: [
      "               ",
      "               ",
      "               ",
      "               ",
      "    ∞          ",
      "  R    @ R R R ",
      "               ",
      "               ",
      "               ",
      "               ",
    ],
    links: {"7,3_label":"SETOR 00","7,7_exitTo":"NEXUS CENTRAL (HUB)","7,7_spawnX":11,"7,7_spawnY":6,"5,9_exitTo":"NEXUS CENTRAL (HUB)","5,9_spawnX":22,"5,9_spawnY":15,"5,9_init":true,"13,5_angle":0,"12,5_dir":3,"12,5_init":true,"12,5_launcher":{"fireRate":120,"rate":2,"channel":0,"dir":3},"9,5_dir":3,"11,5_dir":3,"13,5_dir":3,"11,5_launcher":{"type":"box","projectileType":"box","channel":0,"dir":3,"rotateDir":"CW","autoRotate":8,"fireRate":1,"rate":0.01,"rotateEvery":3},"9,5_launcher":{"type":"antimatter","projectileType":"antimatter","channel":0,"dir":3},"4,4_enemy":{"path":[{"x":4,"y":2},{"x":12,"y":2},{"x":12,"y":6},{"x":4,"y":6},{"x":4,"y":4}]}},
    dialogues: {}
  },
  {
    name: "TESTDRIVE",
    map: [
      "######## ####F ######## # # # # # # ####",
      "#WW       THH                          #",
      "#,,,,,,,,,ccccc                        #",
      "#,    cc ,ccccc ccc#                   #",
      "#  cccc  ,,        #                   #",
      "#******** ,,,  ****#                   #",
      "#                  #                   #",
      "#         a        #                   #",
      "        c   G      #                   #",
      "V F@               #                   #",
      "V B    ^ < > v     #####################",
      "V           ##G##  #####################",
      "V      cc   *****  #####################",
      "V FdC  VV  Gccccccc#####################",
      "V r+l  VV  cc cGc G#####################",
      "V L+J  VV   ccccc G#####################",
      "L HB   VV  c ccccc #####################",
      "#      VV  #############################",
      "#      VV  WWWWWWWW#####################",
      "#      VV       ccc#####################",
      "#      cc          #####################",
      "#                  #####################",
      "#                  #####################",
      "# ******           #####################",
      "# *******          #####################",
      "# *******          #####################",
      "# ********         #####################",
      "#*********         #####################",
      "#*******           #####################",
      "# ******           #####################",
      "# *****##          #####################",
      "#                  #####################",
      "# cc               #####################",
      "#cccc  #######  ########################",
      "#cccc   #          #####################",
      "#       # ####  ########################",
      "#         #  #  #  #####################",
      "#         #        #####################",
      "# # # # ###  #    ######################",
      "########################################",
    ],
    blocks: [
      "💬                                      ",
      "                                      ⚡ ",
      "                                        ",
      "      >                                 ",
      "  >     > y   p                         ",
      "          yy pp                         ",
      "           p  p                         ",
      "                                        ",
      " >            M                         ",
      "                                        ",
      "                                        ",
      "   >       M                            ",
      "                                        ",
      "            MMM   M                     ",
      "             M   M                      ",
      " <       v M     M                      ",
      "      v     M     M                     ",
      "                                        ",
      "                                        ",
      "    >                                   ",
      "  >                                     ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "   p              >                     ",
      " p  y p          >                      ",
      "              ⚡                         ",
      "         >        >                     ",
      " y                                      ",
      "                                        ",
      "        ⚡                               ",
      " ⚡ ⚡ ⚡ ⚡                                ",
      "                                        ",
    ],
    overlays: [
      "        D     D        U U U U U U U    ",
      "    O O _    Q                          ",
      "                 ]                      ",
      "       _    %    ]                      ",
      "   ???           ]                      ",
      "   ???           ]                      ",
      "   ???           ]                      ",
      "   ???    _      ]                      ",
      "D       _ E      ]                      ",
      " _   ))))))))))SSSS                     ",
      "               SSSS                     ",
      "                 SS                     ",
      "       BX                               ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                                        ",
      "                 O                      ",
      "       TT                               ",
      "    ]           wne                     ",
      "    ]            s                      ",
      "    ]                                   ",
      "    ]      ))))))]                      ",
      "    ]     [      ]                      ",
      "    ][    [      ]                      ",
      "    )[    [ ](((((                      ",
      "          [ ]                           ",
      "          [ ]                           ",
      "          [((                           ",
      "  D    ??                               ",
      "       ??                               ",
      "  E                                     ",
      "                                        ",
      "                                        ",
      "   O                                    ",
      "                                        ",
      "                                        ",
      "                                        ",
    ],
    links: {"7,3":2,"2,9_toggle":true,"1,11_toggle":true,"1,9":1,"0,8":1,"7,3_behavior":"TOGGLE","14,1_behavior":"PERMANENT","14,1":3,"14,0":3,"8,1_behavior":"PRESSURE","8,1":4,"8,0":4,"10,7_behavior":"PRESSURE","10,7_init":true,"10,7":8,"5,9":8,"6,9":8,"7,9":8,"8,9":8,"9,9":8,"10,9":8,"11,9":8,"12,9":8,"13,9":8,"14,9":8,"17,2":15,"17,3":15,"17,4":15,"17,5":15,"17,6":15,"17,7":15,"17,8":15,"1,21_dir":0,"7,3_init":false,"8,8":11,"8,8_behavior":"TOGGLE","8,8_init":true,"10,8":11,"14,8_dir":1,"14,8_behavior":"3","3,4":2,"4,4":2,"5,4":2,"3,5":2,"4,5":2,"5,5":2,"3,6":2,"4,6":2,"3,7":2,"4,7":2,"5,7":2,"5,6":2,"17,19":5,"6,1":5,"6,1_color":"#ff0000","17,19_color":"#ff0000","4,1":9,"4,1_color":"#00e1ff","3,36":9,"3,36_color":"#00e1ff","14,13_dir":3,"18,13_dir":1,"18,16_dir":2,"12,16_dir":3,"12,13_dir":0,"13,13_dir":1,"13,14_dir":3,"17,14_dir":1,"17,15_dir":2,"11,15_dir":3,"11,11_dir":0,"7,31":29,"8,31":29,"7,32":29,"8,32":29,"10,8_dir":0,"11,5_dir":1,"10,5_dir":2,"13,5_dir":1,"14,4_dir":2,"2,33_dir":2,"2,33_init":false,"2,33":20,"2,31":20,"23,0_exitTo":"NEXUS CENTRAL (HUB)"},
    dialogues: {"0,0":{"trigger":"start","radius":0,"oneShot":true,"lockPlayer":false,"autoDismiss":true,"messages":[{"text":"Nova fala...","icon":"ai","trigger":"walk","isAI":true}]}},
    zoneTriggers: [{"x":14,"y":33,"radius":1,"oneShot":true,"events":[{"type":"blackout","action":"deactivate"},{"type":"music_intensity","action":"3"},{"type":"earthquake","action":"90"},{"type":"wait","action":"30"}],"w":2,"h":1,"offX":0,"offY":0},{"x":8,"y":37,"radius":1,"oneShot":true,"events":[{"type":"blackout","action":"activate"},{"type":"music_intensity","action":"1"},{"type":"earthquake","action":"90"},{"type":"remote_signal","action":"activate","channel":"20"}],"w":1,"h":2,"offX":0,"offY":-1},{"x":3,"y":38,"radius":0,"oneShot":false,"events":[{"type":"remote_signal","action":"toggle","channel":"20"}]},{"x":5,"y":38,"radius":0,"oneShot":true,"events":[{"type":"gravity","action":"left"}]},{"x":7,"y":38,"radius":0,"oneShot":false,"events":[{"type":"dimension_shift","action":"solar"},{"type":"wait","action":"30"},{"type":"dimension_shift","action":"lunar"}]},{"x":1,"y":38,"radius":0,"oneShot":true,"events":[{"type":"security_alert","action":"activate"},{"type":"wait","action":"200"},{"type":"security_alert","action":"deactivate"}]},{"x":38,"y":1,"radius":0,"oneShot":true,"events":[{"type":"grant_ability","action":"grab","channel":"0"}]}],
    spawnIsStation: true
  },
  {
    name: "PUSH",
    map: [
      "### ################",
      "### ################",
      "### WWWWWWWWWWWW ###",
      "###              ###",
      "###              ###",
      "###   BHHHHHH2   ###",
      "###              ###",
      "###              ###",
      "###              ###",
      "###              ###",
      "###  F@          ###",
      "###  V           ###",
      "###  LHHHHHHZ    ###",
      "####################",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      " 💬                  ",
      "        >  >        ",
      "  �               💬  ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    overlays: [
      "                    ",
      "                    ",
      "   U            D   ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    links: {"17,11_toggle":false,"17,11":1,"17,7":1,"17,9":1,"2,10":2,"2,8":2,"17,6_init":true,"3,2_exitTo":"NEXUS CENTRAL (HUB)"},
    dialogues: {"1,5":{"trigger":"start","pos":"follow","messages":[{"text":"[speed:40][wave:1.5]Sistemas de Superfície...[/wave] [color:#00f0ff]ONLINE.","icon":"ai"},{"text":"Bem-vindo ao [highlight:#ff00ea]SETOR 00[/highlight].[pause:500]\nAperte [color:#ff00ea]ESPAÇO[/color] para prosseguir.","icon":"ai"}]}},
    spawnIsStation: true
  },
  {
    name: "REDIRECT",
    map: [
      "####################",
      "###WWWWWWWWWWWWWW###",
      "###              ###",
      "###              ###",
      "###        FHX   ###",
      "###        V     #WW",
      "###  2HHHHHl   @    ",
      "### ZHHHHHHl     ###",
      "###        LHB   ###",
      "###              ###",
      "###              ###",
      "####################",
      "WWWWWWWWWWWWWWWWWWWW",
      "                    ",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      " 💬      <   <       ",
      "                    ",
      "           <        ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    overlays: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                 U  ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    links: {"17,6_exitTo":2,"17,6_spawnX":3,"17,6_spawnY":12},
    dialogues: {"1,5":{"trigger":"start","messages":[{"text":"[arcane:#00f0ff:#ff00ea]Energia Quântica detectada.[/arcane]\nOs prismas exigem [color:#00f0ff]foco quântico.","icon":"ai"},{"text":"[sfx:human]Alô? [pause:300]Consegue me ouvir?[/sfx]\n[shake:1]A estática está muito forte...[/shake]","icon":"human"}]}}
  },
  {
    name: "COMPLETE",
    map: [
      "################# ##",
      "################# ##",
      "#WWWWWWWWWWWWWWWW W#",
      "#                  #",
      "#                  #",
      "#                  #",
      "#                  #",
      "# BHCSFHCSFHCSFHH5 #",
      "#   L JSL JSL J    #",
      "#                  #",
      "#                  #",
      "# @                #",
      "#                  #",
      "####################",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "       >   >        ",
      "                    ",
      "                    ",
      "     >   >   >      ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    overlays: [
      "                    ",
      "                    ",
      "                 U  ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    dialogues: {"1,5":{"trigger":"start","messages":[{"text":"[speed:10]ESTABILIZANDO PROTOCOLO...[/speed]\n[pause:800]Pronto. Conexão firme.","icon":"ai"},{"text":"[glitch:2]ADVERTÊNCIA![/glitch] [pause:500]\n[pulse:1]Radiação Beta acima do normal.[/pulse]","icon":"alert"}]}}
  },
  {
    name: "DUAL CORE",
    map: [
      "####################",
      "WW#WWWWWWWWWWWWWW#WW",
      "  #     BCFX     #  ",
      "# #     #VV#     # #",
      "# #     #VV#     # #",
      "# #     #VV#     # #",
      "# # @   WVV#     # #",
      "# #      VV#     # ##",
      "# #     #VV#     # #",
      "# #     #VV#     # # ###",
      "# #     #VV#     # #",
      "# #     WVVW     # #",
      "W #     ZJLT     # W",
      "  #              #  ",
      "# ################ #",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "    v               ",
      "          v         ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    dialogues: {"1,5":{"trigger":"start","pos":"follow","messages":[{"text":"O núcleo duplo exige sincronia.\n[crypt:2]ALPHA-9-ZERO[/crypt]","icon":"ai"},{"text":"[shake:2]ALERTA DE PRESSÃO![/shake]\nNão toque nos componentes [color:#ff0000]RED[/color].","icon":"critical"}]}}
  },
  {
    name: "RECEPÇÃO SETOR 01",
    map: [
      "}}}}}}}}}}}}}}}",
      "}{{{{{{{{{{{{{}",
      "}oooooooooo,oo}",
      "}oooooooooo,oo}",
      "}oooooooooo,oo}",
      "}oooooo,,,,,oo}",
      "}oooooo,oooooo}",
      "}oooooo,oooooo}",
      "}}}}}}},}}}}}}}",
      "{{{{{{{U{{{{{{{",
    ],
    overlays: [
      "               ",
      "               ",
      "               ",
      "  @            ",
      "               ",
      "               ",
      "               ",
      "               ",
      "               ",
      "               ",
    ],
    links: {"7,3_label":"SETOR 01","7,7_exitTo":"NEXUS CENTRAL (HUB)","7,9_exitTo":"NEXUS CENTRAL (HUB)","7,9_spawnX":32,"7,9_spawnY":19,"7,9_init":true},
    dialogues: {}
  },
  {
    name: "DIVERSION",
    map: [
      "####################",
      "###WWWWWWWWWWWWWW###",
      "###              ###",
      "### F B HHdHHHX  ###",
      "### V     V      ###",
      "### V     V      ###",
      "### V     2      ###",
      "### V     V      ###",
      "### V     V      ###",
      "### V 3 HHJ      ###",
      "### V            ###",
      "### LH@          ###",
      "###              ###",
      "####################",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "     < <            ",
      "                    ",
      "                    ",
      "                    ",
      "            ^ >     ",
      "                    ",
      "            < v     ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    dialogues: {"1,5":{"trigger":"start","messages":[{"text":"[arcane:2:#00f0ff]Desvio de carga detectado.[/arcane]\nUse os [highlight:#ff00ea]Botões Roxos[/highlight] para alternar.","icon":"ai"},{"text":"[pixel:2]A imagem está pixelando...[/pixel]\n[sfx:human]O sistema está caindo?[/sfx]","icon":"human"}]}}
  },
  {
    name: "MAGNETIC BELT",
    map: [
      "####################",
      "###WWWWWWWWWWWWWW###",
      "###              ###",
      "### @            ###",
      "###   ))))))     ###",
      "###   (    )     ###",
      "###   (    )     ###",
      "###   ((((((     ###",
      "###          B   ###",
      "###   [[[[[[ V   ###",
      "###   ]    [ V   ###",
      "###   ]]]]]] 2   ###",
      "###              ###",
      "####################",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "      >             ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    dialogues: {"1,5":{"trigger":"start","messages":[{"text":"[reboot:2]REINICIALIZANDO ESTEIRA...[/reboot]\n[pause:500]Fluxo magnético reativado.","icon":"ai"},{"text":"Cuidado com a [color:#00f0ff]Gravidade[/color].\nO cinto é implacável.","icon":"ai"}]}}
  },
  {
    name: "SACRIFICE",
    map: [
      "####################",
      "#WWWWWWWWWWWWWW#####",
      "#              #####",
      "#  @           #####",
      "#              #WWW#",
      "#             FHC  #",
      "#             V#V  #",
      "#         B  HJ#V  #",
      "#              #V  #",
      "################V  #",
      "#         #FHHHHJ  #",
      "#         #V       #",
      "#         FT      ##",
      "#                KB#",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "           >        ",
      "                    ",
      "                    ",
      "                    ",
      "              <     ",
      "               >    ",
      "                    ",
      "                    ",
    ],
    overlays: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "  __))))))))   D    ",
      "      ((((((        ",
      "                    ",
      "                    ",
      "                    ",
      "   S   S S          ",
      "     S              ",
      "  S    S            ",
      "   S  S   D         ",
      "                    ",
    ],
    links: {"10,13":0,"2,5":1,"15,5":1,"3,5":1},
    dialogues: {"1,5":{"trigger":"start","pos":"follow","messages":[{"text":"[melt:3]O CALOR ESTÁ DERRETENDO O SENSOR![/melt]","icon":"critical"},{"text":"[sketch:2]A realidade está virando um desenho?[/sketch]\nIsso não estava no manual.","icon":"ai"}]}}
  },
  {
    name: "RECEPÇÃO SETOR 02",
    map: [
      "ΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩ",
      "Ω~~~~~~~~~~~~~Ω{{{{{{{{{ρ{{{{Ω",
      "ΩσσσσσσσσσσσσσΩσσσσσσσσσρσσσσΩ",
      "Ωσσσσσσσσσσσσσ{σσσσσσσσσρσσσσΩ",
      "ΩσσσσσσσσσσσσσσσσσσσσσσσρσσσσΩ",
      "ΩσσσσσσρρρρρρρρρρρρρρρρρρσσσσΩ",
      "ΩσσσσσσρσσσσσσσσσσσσσσσσρσσσσΩ",
      "ΩσσσσσσρσσσσσσΩσσσσσσσσσρσσσσΩ",
      "ΩσσσσσσρσσσσσσΩσσσσσσσσσρσσσσΩ",
      "ΩΩΩΩΩΩΩρΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩΩρΩΩΩΩΩ",
      "{{{{{{{U{{{{{{Σ{{{{{{{{{{{{{{{",
    ],
    overlays: [
      "                              ",
      "                        U     ",
      "                              ",
      "                              ",
      "                              ",
      "           @                  ",
      "                              ",
      "                              ",
      "                              ",
      "                        U     ",
      "                              ",
    ],
    links: {"7,3_label":"SETOR 02","7,7_exitTo":"NEXUS CENTRAL (HUB)","7,9_exitTo":"NEXUS CENTRAL (HUB)","7,9_init":true,"7,9_spawnX":17,"7,9_spawnY":19,"7,8_exitTo":"NEXUS CENTRAL (HUB)","7,10_init":true,"7,10_exitTo":"NEXUS CENTRAL (HUB)","7,10_spawnX":17,"7,10_spawnY":19},
    dialogues: {}
  },
  {
    name: "NEW LEVEL",
    map: [
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAfffffffAAAAffffffffAAAfffffffAAAAAfffffAAAAAAA",
      "AAAAaaaaaaaAAAAaaaaaaaaAAAaaaaaaaAAAAAaaaaaAAAAAAA",
      "AAAAaaaaaaaAAAAaaaaaaaaAAAaaaaaaaAAAAAaaaaaAAAAAAA",
      "AAAAaaaaaaaffffaaaaaaaafffaaaaaaafffffaaaaaAAAAAAA",
      "AAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAAAAA",
      "AAAAaaaaaaaAAAAaaaaaaaaAAAaaaaaaaAAAAAaaaaaAAAAAAA",
      "AAAAaaaaaaaAAAAaaaaaaaaAAAaaaaaaaAAAAAaaaaaAAAAAAA",
      "AAAAAAAAaAAAAAAaaaaaaaaAAAAAAaAAAAAAAAaaaaaAAAAAAA",
      "AAAAAAAAaAAAAAAAaaaaaaAAAAAAAaAAAAAAAAAAAaAAAAAAAA",
      "AAAAAAAAaAAAAAAAaaaaaaAAAAAAAaAAAAAAAffffaffffAAAA",
      "AAAAAAAAaAAAAAAfaaaaaaffAAAffafAAAAAAaaaaaaaaaAAAA",
      "AAAAffffafffAAAaaaaaaaaaAAAaaaaAAAAAAaaaaaaaaaAAAA",
      "AAAAaaaaaaaaAAAaaaaaaaaaAAAaaaaAAAAAAaaaaaaaaaAAAA",
      "AAAAaaaaaaaaAAAaaaaaaaaaAAAaaaaAAAAAAaaaaaaaaaAAAA",
      "AAAAaaaaaaaafffaaaaaaaaafffaaaaffffffaaaaaaaaaAAAA",
      "AAAAaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaAAAA",
      "AAAAaaaaaaaaAAAaaaaaaaaaAAAaaaaAAAAAAaaaaaaaaaAAAA",
      "AAAAaaaaaaaaAAAaaaaaaaaaAAAaaaaAAAAAAaaaaaaaaaAAAA",
      "AAAAaaaaaaaaAAAaaaaaaaaaAAAaaaaAAAAAAaaaaaaaaaAAAA",
      "AAAAAAAaAAAAAAAAAaaaaaAAAAAaaaaAAAAAAAAAAaAAAAAAAA",
      "AAAAAAAaAAAAAAAAAaaaaaAAAAAAAAaAAAAAAAAAAaAAAAAAAA",
      "AAAAAAAaAAAAAAAAAaaaaaAAAAAAAAaAAAAAfffffaffffAAAA",
      "AAAAAffaffAAAAAAAaaaaaAAAAffffafffAAaaaaaaaaaaAAAA",
      "AAAAAaaaaaAAAAAAAaaaaaAAAAaaaaaaaaAAaaaaaaaaaaAAAA",
      "AAAAAaaaaaAAAAAAAaaaaaffffaaaaaaaaAAaaaaaaaaaaAAAA",
      "AAAAAaaaaafffffffaaaaaaaaaaaaaaaaaffaaaaaaaaaaAAAA",
      "AAAAAaaaaaaaaaaaaaaaaaAAAAaaaaaaaaaaaaaaaaaaaaAAAA",
      "AAAAAaaaaaAAAAAAAaaaaaAAAAaaaaaaaaAAaaaaaaaaaaAAAA",
      "AAAAAaaaaaAAAAAAAaaaaaAAAAaaaaaaaaAAAAAAAaAAAAAAAA",
      "AAAAAaaaaaAAAAAAAaaaaaAAAAAAAaAAAAAAAAAAAaAAAAAAAA",
      "AAAAAAAAaAAAAAAAAaaaaaAAAAAAAaAAAAAAAAAAAaAAAAAAAA",
      "AAAAffffafffAAAAAaaaaaAAAAAAAaAAAAAAAAAAAaAAAAAAAA",
      "AAAAaaaaaaaaAAAAfaaaaafAAAAAAaAAAAAAAffffafffAAAAA",
      "AAAAaaaaaaaaAAAAaaaaaaaAAAfffaffAAAAAaaaaaaaaAAAAA",
      "AAAAaaaaaaaaAAAAaaaaaaaAAAaaaaaaAAAAAaaaaaaaaAAAAA",
      "AAAAaaaaaaaaAAAAaaaaaaafffaaaaaaAAAAAaaaaaaaaAAAAA",
      "AAAAaaaaaaaaffffaaaaaaaaaaaaaaaafffffaaaaaaaaAAAAA",
      "AAAAaaaaaaaaaaaaaaaaaaaAAAaaaaaaaaaaaaaaaaaaaAAAAA",
      "AAAAaaaaaaaaAAAAaaaaaaaAAAaaaaaaAAAAAaaaaaaaaAAAAA",
      "AAAAaaaaaaaaAAAAaaaaaaaAAAaaaaaaAAAAAAAAAAAAAAAAAA",
      "AAAAaaaaaaaaAAAAaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAaaaaaaaaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ],
    overlays: [
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                         S        ",
      "       @         S         S T         ST         ",
      "                 S                                ",
      "                                         S        ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "     S            S                    S   S      ",
      "                            S                     ",
      "         S         T         T                    ",
      "                  S         S                     ",
      "      S                      S                    ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "        S                               S         ",
      "                   T       S                      ",
      "       T           S       SS                     ",
      "                                                  ",
      "      S                                           ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "      S                                           ",
      "                 S                                ",
      "     S                                            ",
      "                   S         S         S  S       ",
      "                 S          ST           S        ",
      "       S                                          ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
    ],
    links: {"6,22_label":"SETOR D3","38,37_label":"SETOR I8"}
  },
  {
    name: "RECEPÇÃO SETOR 03",
    map: [
      "|||||||||||||||",
      "|\"\"\"\"\"\"\"\"\"\"\"\"\"|",
      "|'''''''''''''|",
      "|'''''|||'''''|",
      "|.''''|||'''''|",
      "|..'''|||'''''|",
      "|.''''\"\"\"'''''|",
      "|..'''''''''''|",
      "|||||||'|||||||",
      "\"\"\"\"\"\"'U'\"\"\"\"\"\"\"\"",
    ],
    overlays: [
      "               ",
      "               ",
      "               ",
      "            @  ",
      " ?             ",
      "               ",
      " ?             ",
      " ??            ",
      "               ",
      "      B B      ",
    ],
    links: {"7,3_label":"SETOR 03","7,7_exitTo":"NEXUS CENTRAL (HUB)","7,9_exitTo":"NEXUS CENTRAL (HUB)"},
    dialogues: {}
  },
  {
    name: "THE PIT",
    map: [
      "####################",
      "#WWWWWWWWWWWWWWWWWW#",
      "#                  #",
      "#   BHHHHHHHHH2    #",
      "#                  #",
      "#   *****?****     #",
      "#   *****?****     #",
      "#   *****?****     #",
      "#        _         #",
      "#      @           #",
      "#                  #",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "        >           ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    overlays: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "   ))))     ((((    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "  G                 ",
      "                    ",
    ],
    links: {"9,8":1,"9,5":1,"9,6":1,"9,7":1}
  },
  {
    name: "SINGULARIDADE",
    map: [
      "####################",
      "#WWWWWWWWWWWWWWWWWW#",
      "#                  #",
      "# BHHH    T1   B   #",
      "#              V   #",
      "#              V   #",
      "#              V   #",
      "#              V   #",
      "#              V   #",
      "#     @        T1  #",
      "#                  #",
      "####################",
    ],
    blocks: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "    y               ",
      "         p          ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ],
    overlays: [
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "       |            ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
      "                    ",
    ]
  },
  {
    name: "RECEPÇÃO SETOR 04",
    map: [
      "NNNNNNNNNNNNNNN",
      "NgggggggggggggN",
      "NtttttttttttttN",
      "NtttttttttttttN",
      "NtttttttttttttN",
      "NtttttttttttttN",
      "NtttttttttttttN",
      "NtttttttttttttN",
      "NNNNNNtttNNNNNN",
      "ggggggtUtgggggg",
    ],
    overlays: [
      "               ",
      "               ",
      "               ",
      "           @   ",
      "               ",
      "               ",
      "               ",
      "               ",
      "               ",
      "      B B      ",
    ],
    links: {"7,3_label":"SETOR 04","7,7_exitTo":"NEXUS CENTRAL (HUB)","7,9_exitTo":"NEXUS CENTRAL (HUB)"},
    dialogues: {}
  },
  {
    name: "RECEPÇÃO SETOR 05",
    map: [
      "###############",
      "#WWWWWWWWWWWWW#",
      "#             #",
      "#      !      #",
      "#             #",
      "#      @      #",
      "#             #",
      "#     BUB     #",
      "#             #",
      "###############",
    ],
    links: {"7,3_label":"SETOR 05","7,7_exitTo":"NEXUS CENTRAL (HUB)"}
  },
  {
    name: "RECEPÇÃO SETOR 06",
    map: [
      "YYYYYYYYYYYYYYY",
      "YhhhmmmmhhmhmhY",
      "YcccccccccccccY",
      "YcccccccccccccY",
      "YcccccccccccccY",
      "YcccccccccccccY",
      "YcccccccccccccY",
      "YcccccccccccccY",
      "YcccccccccccccY",
      "YYYYYYYUYYYYYYY",
    ],
    overlays: [
      "               ",
      "               ",
      "               ",
      "               ",
      "       @       ",
      "               ",
      "               ",
      "               ",
      "               ",
      "      B B      ",
    ],
    links: {"7,3_label":"SETOR 06","7,7_exitTo":"NEXUS CENTRAL (HUB)","7,9_exitTo":"NEXUS CENTRAL (HUB)"},
    dialogues: {}
  },
  {
    name: "RECEPÇÃO SETOR 07",
    map: [
      "IIIIIIIIIIIIIII",
      "Ikjjjjjjjj jjkI",
      "IbbbbbbbbbbbbbI",
      "IbbbbbbbbbbbbbI",
      "IbbbbbbbbbbbbbI",
      "IbbbbbbbbbbbbbI",
      "IbbbbbbbbbbbbbI",
      "IbbbbbbbbbbbbbI",
      "IbbbbbbbbbbbbbI",
      "IIbUbIIIIIIIIII",
    ],
    overlays: [
      "               ",
      "          U    ",
      "               ",
      "               ",
      "       @       ",
      "               ",
      "               ",
      "               ",
      "               ",
      "  B B          ",
    ],
    links: {"7,3_label":"SETOR 07","7,7_exitTo":"NEXUS CENTRAL (HUB)","3,9_exitTo":"NEXUS CENTRAL (HUB)"},
    dialogues: {}
  },
  {
    name: "RECEPÇÃO SETOR 08",
    map: [
      "===============",
      "=;;;;;;;;;;;;;=",
      "=&&&&&&&&&&&&&=",
      "=&&&&&&&&&&&&&=",
      "=&&&&&&&&&&&&&=",
      "=&&&&&&&&&&&&&=",
      "=&&&&&&&&&&&&&=",
      "=&&&&&&&&&&&&&=",
      "=&&&&&&&&&&&&&=",
      "=======U=======",
    ],
    overlays: [
      "               ",
      "               ",
      "               ",
      "               ",
      "               ",
      "       @       ",
      "               ",
      "               ",
      "               ",
      "      B B      ",
    ],
    links: {"7,3_label":"SETOR 08","7,7_exitTo":"NEXUS CENTRAL (HUB)","7,9_exitTo":"NEXUS CENTRAL (HUB)"},
    dialogues: {}
  },
  {
    name: "RECEPÇÃO SETOR 09",
    map: [
      "..xxxxxxxxxxxxx",
      "...qqq...qqqqqx",
      "....zz..zzzzzzx",
      "...zzz.zzzzzz.x",
      "....zzzzzzzz..x",
      "...zzzzzzzzz...",
      "..zzzzzzzzzzz..",
      "x.z..zzzzzzz...",
      "x.z.zzzzzzzz...",
      "xxxxxxzUzxxxx..",
    ],
    overlays: [
      "               ",
      "               ",
      "               ",
      "               ",
      "               ",
      "       @       ",
      "               ",
      "               ",
      "               ",
      "      B B      ",
    ],
    links: {"7,3_label":"SETOR 09","7,7_exitTo":"NEXUS CENTRAL (HUB)","7,9_exitTo":"NEXUS CENTRAL (HUB)","7,9_spawnX":29,"7,9_spawnY":28},
    dialogues: {}
  },
  {
    name: "CORREDOR DE CADÊNCIA",
    map: [
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
      "AaaaaaaaaaaaaaaaaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaaaaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaaaaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaaaaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaaaaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaaaaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaaaaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaaaaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaaaaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaaaaaaaaaaaaaaaaA",
      "AaaaaaaaaaaaaaaaaaaaaaaaaaaaaA",
      "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    ],
    overlays: [
      "                              ",
      "                              ",
      "  @                           ",
      "      R   R   R               ",
      "                              ",
      "              R   R   R       ",
      "                              ",
      "      R   R   R               ",
      "                              ",
      "              R   R   R       ",
      "                              ",
      "      R   R   R             U ",
      "                              ",
    ],
    links: {"6,3_launcher":{"type":"energy","rate":2,"fireRate":120,"speed":4,"delay":0,"initialDelay":0},"10,3_launcher":{"type":"energy","rate":2,"fireRate":120,"speed":4,"delay":0,"initialDelay":0},"14,3_launcher":{"type":"energy","rate":2,"fireRate":120,"speed":4,"delay":0,"initialDelay":0},"14,5_launcher":{"type":"box","rate":2,"fireRate":120,"speed":3,"delay":0,"initialDelay":0},"18,5_launcher":{"type":"box","rate":2,"fireRate":120,"speed":3,"delay":1,"initialDelay":60},"22,5_launcher":{"type":"box","rate":2,"fireRate":120,"speed":3,"delay":0,"initialDelay":0},"6,7_launcher":{"type":"energy","rate":1.5,"fireRate":90,"speed":5,"delay":0,"initialDelay":0},"10,7_launcher":{"type":"energy","rate":1.5,"fireRate":90,"speed":5,"delay":0.3,"initialDelay":18},"14,7_launcher":{"type":"energy","rate":1.5,"fireRate":90,"speed":5,"delay":0.6,"initialDelay":36},"14,9_launcher":{"type":"energy","rate":0.6,"fireRate":36,"speed":7,"delay":0,"initialDelay":0},"18,9_launcher":{"type":"energy","rate":0.6,"fireRate":36,"speed":7,"delay":0.2,"initialDelay":12},"22,9_launcher":{"type":"energy","rate":0.6,"fireRate":36,"speed":7,"delay":0.4,"initialDelay":24},"6,11_launcher":{"type":"antimatter","rate":3,"fireRate":180,"speed":2.5,"delay":0,"initialDelay":0},"10,11_launcher":{"type":"antimatter","rate":3,"fireRate":180,"speed":2.5,"delay":1,"initialDelay":60},"14,11_launcher":{"type":"antimatter","rate":3,"fireRate":180,"speed":2.5,"delay":2,"initialDelay":120},"28,11_exitTo":"NEXUS CENTRAL (HUB)"}
  },
  {
    name: "NEXUS CENTRAL (HUB)",
    map: [
      "##################################################",
      "#                                                #",
      "#                                                #",
      "#                                                #",
      "#                        $                       #",
      "#                                                #",
      "#                                                #",
      "#                                                #",
      "#                                                #",
      "#           AAAAAAAAAAAAAAAAAAAAAAAAAA           #",
      "#           A                        A           #",
      "#           A                        A           #",
      "#           A                        A           #",
      "#           A         !    !         A           #",
      "#           A        BUB   U         A           #",
      "#           A                        A           #",
      "#           A           @            A           #",
      "#           A    !              !    A           #",
      "#           A   BUB            BUB   A           #",
      "#     !     A           $            A           #",
      "#    BUB    A                        A           #",
      "#           A                        A           #",
      "#           AAAAAAAAAAAAAAAAAAAAAAAAAA           #",
      "#     !                                    !     #",
      "#    BUB                                  BUB    #",
      "#                                                #",
      "#          !                 !                   #",
      "#         BUB               BUB       U          #",
      "#                                                #",
      "#                                                #",
      "#                                                #",
      "##################################################",
    ],
    overlays: [
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                          B B                     ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
      "                                                  ",
    ],
    links: {"11,4_label":"SETOR 00","11,5_exitTo":"RECEPÇÃO SETOR 00","43,19_label":"SETOR 01","43,20_exitTo":"RECEPÇÃO SETOR 01","6,8_label":"SETOR 02","6,9_exitTo":"RECEPÇÃO SETOR 02","43,8_label":"SETOR 03","43,9_exitTo":"RECEPÇÃO SETOR 03","6,19_label":"SETOR 04","6,20_exitTo":"RECEPÇÃO SETOR 04","29,4_label":"SETOR 05","29,5_exitTo":"RECEPÇÃO SETOR 05","6,23_label":"SETOR 06","6,24_exitTo":"RECEPÇÃO SETOR 06","43,23_label":"SETOR 07","43,24_exitTo":"RECEPÇÃO SETOR 07","11,26_label":"SETOR 08","11,27_exitTo":"RECEPÇÃO SETOR 08","29,26_label":"CORE","29,27_exitTo":"RECEPÇÃO SETOR 09","38,4_exitTo":"RECEPÇÃO SETOR 01","38,27_exitTo":"RECEPÇÃO SETOR 05","22,14_label":"SETOR 00","22,15_exitTo":"RECEPÇÃO SETOR 00","17,18_label":"SETOR 02","17,19_exitTo":"RECEPÇÃO SETOR 02","24,11_label":"SETOR 00","24,12_exitTo":"RECEPÇÃO SETOR 00","19,15_label":"SETOR 02","19,16_exitTo":"RECEPÇÃO SETOR 02","22,11_label":"SETOR 00","22,12_exitTo":"RECEPÇÃO SETOR 00","17,15_label":"SETOR 02","17,16_exitTo":"RECEPÇÃO SETOR 02","22,13_label":"SETOR 00","22,14_exitTo":"RECEPÇÃO SETOR 00","17,17_label":"SETOR 02","17,18_exitTo":"RECEPÇÃO SETOR 02","21,13_label":"SETOR 00","21,14_exitTo":"RECEPÇÃO SETOR 00","16,17_label":"SETOR 02","16,18_exitTo":"RECEPÇÃO SETOR 02","22,12_label":"SETOR 00","22,13_exitTo":"RECEPÇÃO SETOR 00","17,16_label":"SETOR 02","17,17_exitTo":"RECEPÇÃO SETOR 02","21,12_label":"SETOR 00","21,13_exitTo":"RECEPÇÃO SETOR 00","16,16_label":"SETOR 02","16,17_exitTo":"RECEPÇÃO SETOR 02","23,13_label":"SETOR 00","23,14_exitTo":"RECEPÇÃO SETOR 00","18,17_label":"SETOR 02","18,18_exitTo":"RECEPÇÃO SETOR 02","32,18_exitTo":"RECEPÇÃO SETOR 03","28,14_exitTo":"RECEPÇÃO SETOR 03","27,14_exitTo":"RECEPÇÃO SETOR 01","26,14_exitTo":"RECEPÇÃO SETOR 03","31,17_label":"SETOR 03","31,18_exitTo":"RECEPÇÃO SETOR 03","32,17_label":"SETOR 03","27,13_exitTo":"RECEPÇÃO SETOR 00","27,13_label":"SETOR 03","22,14_spawnX":5,"22,14_spawnY":8,"17,18_spawnX":7,"17,18_spawnY":8,"27,14_spawnX":7,"27,14_spawnY":8,"32,18_spawnX":7,"32,18_spawnY":8},
    dialogues: {}
  }
];

var CHAPTERS = [
  {
    "name": "TRIAGEM DE CARGA E FLUXO ESTÁTICO",
    "levels": [
      0,
      1,
      2,
      3,
      4,
      5
    ]
  },
  {
    "name": "LOGÍSTICA DE CONTENÇÃO PRIMÁRIA",
    "levels": [
      6,
      7,
      8,
      9
    ]
  },
  {
    "name": "PAVILHÃO DE PROCESSAMENTO EM FLUXO",
    "levels": [
      10,
      11
    ]
  },
  {
    "name": "ABISMO DE SUSTENTAÇÃO QUÂNTICA",
    "levels": [
      12,
      13,
      14
    ]
  },
  {
    "name": "LABORATÓRIO DE REFRAÇÃO E CONVERGÊNCIA",
    "levels": [
      15
    ]
  },
  {
    "name": "ZONA DE OBSERVAÇÃO DO VÁCUO",
    "levels": [
      16
    ]
  },
  {
    "name": "HUB DE ENTRELAÇAMENTO NÃO-EUCLIDIANO",
    "levels": [
      17
    ]
  },
  {
    "name": "ÁREA DE TESTES: VETORES DE GRAVIDADE",
    "levels": [
      18
    ]
  },
  {
    "name": "CÂMARA DE DEPURAÇÃO DE REALIDADE",
    "levels": [
      19
    ]
  },
  {
    "name": "O COMPILADOR MESTRE",
    "levels": [
      20
    ]
  },
  {
    "name": "CÂMARA DE BALÍSTICA APLICADA",
    "levels": [
      21
    ]
  }
];
